#!/usr/bin/env bash
# run-local: Start Django server locally

set -e

if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi

pip install -r requirements.txt
python manage.py migrate
python manage.py runserver 0.0.0.0:8000
