# Generated by Django 6.0.2 on 2026-02-15 16:14

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Longitude, Latitude coordinates', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0, 'Distance cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90, 'Latitude must be at least -90 degrees.'), django.core.validators.MaxValueValidator(90, 'Latitude must be at most 90 degrees.')]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180, 'Longitude must be at least -180 degrees.'), django.core.validators.MaxValueValidator(180, 'Longitude must be at most 180 degrees.')]),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='choices',
            field=models.JSONField(default=list, help_text='List of available answer choices'),
        ),
        migrations.AlterField(
            model_name='triviaquestion',
            name='correct_answer',
            field=models.CharField(help_text='Must be one of the values from the choices list', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('distance__gte', 0), ('distance__isnull', False), ('latitude__gte', -90), ('latitude__isnull', False), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__isnull', False), ('longitude__lte', 180)), models.Q(('distance__isnull', True), ('latitude__isnull', True), ('longitude__isnull', True)), _connector='OR'), name='valid_geo_coordinates_and_distance'),
        ),
    ]
